import javax.swing.JMenuItem;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wissam
 */
public class MenuAdmin extends javax.swing.JFrame {

    LoginUser luser; // the login user details are obtained from the Login form

    /**
     * Creates new form Menu
     */
    public MenuAdmin(LoginUser user) {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem7.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
       		 (new ViewArtistDetails()).setVisible(true);

        	}
        });
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem8.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 (new ViewSongsByYear()).setVisible(true);
        	}
        });
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem9.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		(new ViewSongsByGenre()).setVisible(true);
        	}
        });
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu3.setText("Artist");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - Music");
        setResizable(true);

       jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.jpg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
       // jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/logout.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
    //    jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/close.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);
        
        mntmAddUpdate = new JMenuItem();
        mntmAddUpdate.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		(new ModifyUser()).setVisible(true);
        		
        	}
        });
        mntmAddUpdate.setText("Add / Update User");
        mntmAddUpdate.setFont(new Font("Arial Rounded MT Bold", Font.PLAIN, 24));
        jMenu1.add(mntmAddUpdate);

        jMenu2.setText("Song");
        jMenu2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jMenuItem3.setText("Add New Song");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jMenuItem5.setText("Update/Delete Song");
       jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);
        
        mntmNewMenuItem = new JMenuItem("View Songs");
        mntmNewMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		   (new ViewSongs()).setVisible(true);
        	}
        });
        mntmNewMenuItem.setFont(new Font("Arial Rounded MT Bold", Font.PLAIN, 24));
        jMenu2.add(mntmNewMenuItem);

        setJMenuBar(jMenuBar1);
        
        jMenu3.setText("Artist");
        jMenu3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        
        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        jMenuItem11.setText("Add Artist");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        jMenuItem7.setText("View Artist Stats");
//        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem7ActionPerformed(evt);
//            }
//        });
        jMenu3.add(jMenuItem7);
        
        jMenuBar1.add(jMenu3);
        
        jMenu5.setText("Genre");
        jMenu5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        jMenuItem10.setText("Add Genre");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);
        jMenuBar1.add(jMenu5);
        
        jMenuItemEditGenre = new JMenuItem();
        jMenuItemEditGenre.setText("Update Genre");
        jMenuItemEditGenre.setFont(new Font("Arial Rounded MT Bold", Font.PLAIN, 24));
        jMenu5.add(jMenuItemEditGenre);
        jMenuItemEditGenre.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem222ActionPerformed(evt);
            }
        });

        jMenu4.setText("Statistics");
        jMenu4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        jMenuItem8.setText("Songs Released per Year");
//        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem8ActionPerformed(evt);
//            }
//        });
        jMenu4.add(jMenuItem8);
        
        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24));
        jMenuItem9.setText("Songs per Genre");
//        jMenuItem9.addActionListener(new java.awt.event.ActionListener()  {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jMenuItem9ActionPerformed(evt);
//            }
//        });
        jMenu4.add(jMenuItem9);
        
        jMenuBar1.add(jMenu4);
        


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        (new LoginForm()).setVisible(true);
        this.dispose(); // the Menu form is disposed ONLY when the currently logged in user logs out
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
   private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      // TODO add your handling code here:
   (new AddSong()).setVisible(true);   

     
    		   }//GEN-LAST:event_jMenuItem3ActionPerformed

   private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
	      // TODO add your handling code here:
	   (new EditSongs()).setVisible(true);  
   }
   
   private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       (new addGenre()).setVisible(true);
   }//GEN-LAST:event_jMenuItem15ActionPerformed

   private void  jMenuItem222ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       (new ViewUpdateGenre()).setVisible(true);
   }
   private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       (new addArtist()).setVisible(true);
       }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private JMenuItem mntmNewMenuItem;
    private JMenuItem mntmAddUpdate;
    private JMenuItem jMenuItemEditGenre;
}